// 이 파일은 외부 Claude JSON의 런타임 스키마를 수용하는 독립 렌더링 어댑터다.
// @ts-nocheck
/**
 * 원본 리바랩스 PDF 재현 전용 렌더러 v2.
 * 기존 lib/pdf/의 ReportDocument·sections·charts를 전혀 사용하지 않는다.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { Circle, Document, Font, Line, Page, Polygon, StyleSheet, Svg, Text, View, renderToBuffer } from "@react-pdf/renderer";
import { parseWallaWorkbook } from "../lib/walla/parse";
import { normalizeWallaRows } from "../lib/walla/normalize";
import { computeQuantStats } from "../lib/quant/compute";
import { buildSurveyQuestionRows } from "../lib/pipeline/surveyQuestions";

let overviewQuestions: { stage: string; question: string }[] = [];

const fontDir = path.join(process.cwd(), "public", "fonts");
Font.register({ family: "ReferenceNoto", fonts: [
  { src: path.join(fontDir, "NotoSansKR-Regular.woff"), fontWeight: "normal" },
  { src: path.join(fontDir, "NotoSansKR-Bold.woff"), fontWeight: "bold" },
] });
const C = { blue: "#5d76ad", pale: "#dce4f6", cyan: "#42c5e5", mint: "#81ebcf", line: "#7d91b9" };
const s = StyleSheet.create({ page:{ paddingTop:31, paddingHorizontal:44, paddingBottom:35, fontFamily:"ReferenceNoto", fontSize:9 }, footer:{ position:"absolute", left:44, right:44, bottom:18, borderTopWidth:.5, borderTopColor:"#889", paddingTop:7, flexDirection:"row", justifyContent:"space-between", fontSize:7 }, banner:{ flexDirection:"row", width:225, height:34, marginBottom:15 }, badge:{ width:36, backgroundColor:"#e5ecf8", color:"#195683", fontSize:16, textAlign:"center", paddingTop:7 }, title:{ flex:1, backgroundColor:C.blue, color:"white", fontSize:15, fontWeight:"bold", textAlign:"center", paddingTop:7 }, sub:{ flexDirection:"row", borderWidth:.7, borderColor:C.line, height:30, marginBottom:16 }, no:{ width:38, backgroundColor:C.pale, textAlign:"center", paddingTop:7, fontWeight:"bold" }, subText:{ flex:1, padding:6, fontSize:13, fontWeight:"bold" }, question:{ fontSize:12, fontWeight:"bold", marginBottom:10 }, chart:{ borderWidth:.5, borderColor:"#aaa", borderTopWidth:0, height:215, padding:13 }, chartHead:{ backgroundColor:"#bdcae8", textAlign:"center", fontSize:11, fontWeight:"bold", paddingVertical:5 }, bars:{ flex:1, flexDirection:"row", alignItems:"flex-end", justifyContent:"space-around", borderBottomWidth:.5, borderBottomColor:"#999", paddingTop:25 }, barWrap:{ width:55, alignItems:"center", justifyContent:"flex-end", height:155 }, bar:{ width:38, backgroundColor:C.mint }, value:{ fontSize:8, fontWeight:"bold", marginBottom:2 }, label:{ fontSize:6.5, marginTop:4, textAlign:"center" }, table:{ marginTop:18, borderTopWidth:.8, borderLeftWidth:.8, borderColor:"#222" }, row:{ flexDirection:"row" }, cell:{ flex:1, minHeight:29, borderRightWidth:.5, borderBottomWidth:.5, borderColor:"#222", textAlign:"center", padding:7 }, head:{ backgroundColor:C.pale, fontWeight:"bold" } });
function Footer({ n }: {n:number}) { return <View style={s.footer} fixed><Text>2025 by Alphabrothers</Text><Text>- {n} -</Text><Text style={{fontWeight:"bold"}}>ALPHA BROTHERS</Text></View>; }
function Header({ roman, title, number, subtitle }:{roman:string,title:string,number:string,subtitle:string}) { return <><View style={s.banner}><Text style={s.badge}>{roman}</Text><Text style={s.title}>{title}</Text></View><View style={s.sub}><Text style={s.no}>{number}</Text><View style={{flex:1,justifyContent:"center",paddingHorizontal:10}}><Text style={{fontSize:13,fontWeight:"bold",color:"#111"}}>{subtitle}</Text></View></View></>; }
const SW_APP_TOC = [
  ["I. 개요", "3", ["1. 제품 소개|3", "2. 사용성 테스트 진행 일정|4", "3. 사용성 테스트 설문 항목|4"]],
  ["II. 인적 사항 및 특성 조사", "6", []],
  ["III. 기능별 고객 경험 평가", "8", ["1. 기능별 고객 경험 조사 결과|8", "2. 기능별 고객 경험 분석|29"]],
  ["IV. 핵심구매요소", "30", ["1. 핵심구매요소 조사 결과|30", "2. 핵심구매요소 분석|31"]],
  ["V. 4대 가치 만족도", "32", ["1. 4대 가치 조사 결과|32", "2. 4대 가치 조사 결과 분석|36"]],
  ["VI. 사용자 경험 품질 평가", "37", ["1. 사용자 경험 품질 평가 결과|37", "2. 사용자 경험 품질 평가 결과 분석|39"]],
  ["VII. 교차 분석", "41", ["1. 사용자 경험 품질 평가 결과 분석|41"]],
  ["VIII. 종합 만족도 및 NPS 지수", "43", ["1. 종합 만족도 및 NPS 지수|43", "2. 개선 아이디어|45"]],
  ["IX. 종합 결과 및 제언", "50", ["1. 사용성테스트 결과 요약|50", "2. 개선 전략 제언|53", "3. 기능별 고객 제언 종합|55"]],
] as const;
function TocLine({label,page,major=false}:{label:string,page:string,major?:boolean}) { return <View style={{flexDirection:"row",alignItems:"baseline",marginTop:major?14:5}}><Text style={{fontSize:major?13:10.5,fontWeight:major?"bold":"normal",color:major?"#1662a2":"#111"}}>{label}</Text><View style={{flex:1,borderBottomWidth:.6,borderBottomColor:"#999",borderStyle:"dotted",marginHorizontal:8}}/><Text style={{fontSize:major?12:10}}>{page}</Text></View>; }
function TocPage() { return <><Page size="A4" style={s.page}><View style={{marginTop:18}}>{SW_APP_TOC.map(([title,page,children])=><View key={title}><TocLine label={title} page={page} major/>{children.map((x)=>{const [label,p]=x.split("|");return <TocLine key={x} label={label} page={p}/>;})}</View>)}</View><Footer n={2}/></Page><OverviewPage/><SurveyOutlinePage pageNo={4} rows={overviewQuestions.slice(0,15)}/><SurveyOutlinePage pageNo={5} rows={overviewQuestions.slice(15)}/></>; }
const tableCell={borderRightWidth:.45,borderBottomWidth:.45,borderColor:C.line,padding:5,fontSize:8};
function OverviewPage() { const pair=(a:string,b:string)=><View style={{flexDirection:"row"}}><Text style={[tableCell,{width:94,backgroundColor:C.pale,textAlign:"center",fontWeight:"bold"}]}>{a}</Text><Text style={[tableCell,{flex:1,textAlign:"center",color:"#666"}]}>{b}</Text></View>; return <Page size="A4" style={s.page}><Header roman="I" title="개요" number="1" subtitle="제품 소개"/><View style={{borderTopWidth:.6,borderLeftWidth:.6,borderColor:C.line}}><Text style={[tableCell,{backgroundColor:C.pale,fontSize:12,fontWeight:"bold",textAlign:"center"}]}>기업 개요</Text><View style={{flexDirection:"row"}}><View style={{flex:1}}>{pair("기업명","입력 필요")}{pair("대표자","입력 필요")}</View><View style={{flex:1}}>{pair("홈페이지","입력 필요")}{pair("업무 담당자","입력 필요")}</View></View></View><View style={{marginTop:9,borderTopWidth:.6,borderLeftWidth:.6,borderColor:C.line}}><Text style={[tableCell,{backgroundColor:C.pale,fontSize:12,fontWeight:"bold",textAlign:"center"}]}>제품 및 서비스 개요</Text>{pair("서비스 명","입력 필요")}{pair("서비스 요약","입력 필요")}{pair("사업 영역","입력 필요")}{pair("산업 분야","입력 필요")}{pair("운영 환경","입력 필요")}{pair("사업화 단계","입력 필요")}</View><View style={{marginTop:10,borderTopWidth:.6,borderLeftWidth:.6,borderColor:C.line,minHeight:245,flexDirection:"row"}}><Text style={[tableCell,{width:94,backgroundColor:C.pale,fontSize:12,fontWeight:"bold",textAlign:"center",paddingTop:104}]}>주요 기능</Text><View style={{flex:1,padding:12}}><Text style={{fontSize:9,color:"#666",lineHeight:1.65}}>제품 이미지 및 주요 기능 설명은 제품 정보가 입력되면 이 영역에 원본과 같은 3단 이미지 행 및 번호 목록 형식으로 배치됩니다.</Text></View></View><Footer n={3}/></Page>; }
function SurveyOutlinePage({pageNo,rows}:{pageNo:number,rows:{stage:string,question:string}[]}) { return <Page size="A4" style={s.page}>{pageNo===4 && <><Header roman="I" title="개요" number="2" subtitle="사용성 테스트 진행 일정"/><View style={{marginBottom:35}}>{["테스트 진행 기간","테스트 대상","담당자"].map(x=><Text key={x} style={{fontSize:10,marginBottom:8}}>•　{x} : <Text style={{color:"#666"}}>입력 필요</Text></Text>)}</View><View style={s.sub}><Text style={s.no}>3</Text><View style={{flex:1,justifyContent:"center",paddingHorizontal:10}}><Text style={{fontSize:13,fontWeight:"bold"}}>사용성 테스트 설문 항목</Text></View></View></>}<View style={{borderTopWidth:.6,borderLeftWidth:.6,borderColor:C.line}}><View style={{flexDirection:"row",backgroundColor:"#bdcae8"}}><Text style={[tableCell,{width:120,fontSize:10,fontWeight:"bold",textAlign:"center"}]}>단계</Text><Text style={[tableCell,{flex:1,fontSize:10,fontWeight:"bold",textAlign:"center"}]}>주요 활동</Text></View>{rows.map((q,i)=><View key={`${q.stage}-${q.question}`} style={{flexDirection:"row",minHeight:31}}><Text style={[tableCell,{width:120,textAlign:"center",fontWeight:i===0||rows[i-1].stage!==q.stage?"bold":"normal"}]}>{i===0||rows[i-1].stage!==q.stage?q.stage:""}</Text><Text style={[tableCell,{flex:1,paddingLeft:10}]}>{`Q${overviewQuestions.indexOf(q)+1}　${q.question}`}</Text></View>)}</View><Footer n={pageNo}/></Page>; }
function BarChart({items, max=40, suffix="%", yLabel="비율"}:{items:{label:string,value:number}[],max?:number,suffix?:string,yLabel?:string}) {
  const ticks=Array.from({length:5},(_,i)=>Math.round(max/4*i));
  return <><Text style={s.chartHead}>[ 응답 결과 ]</Text><View style={s.chart}><Text style={{position:"absolute",left:5,top:105,fontSize:6,transform:"rotate(-90deg)"}}>{yLabel}</Text><View style={{marginLeft:30,height:160,borderBottomWidth:.7,borderLeftWidth:.7,borderColor:"#999",position:"relative"}}>{ticks.map(t=><View key={t} style={{position:"absolute",left:0,right:0,bottom:`${t/max*100}%`,borderTopWidth:.35,borderColor:"#d8d8d8"}}><Text style={{position:"absolute",right:"100%",width:24,textAlign:"right",fontSize:6,top:-3}}>{t}{suffix}</Text></View>)}<View style={{height:160,flexDirection:"row",alignItems:"flex-end",justifyContent:"space-around",paddingHorizontal:10}}>{items.map(x=><View key={x.label} style={{width:Math.min(58,360/items.length),height:160,alignItems:"center",justifyContent:"flex-end"}}><Text style={s.value}>{x.value}{suffix}</Text><View style={[s.bar,{height:Math.max(2,x.value/max*135),width:Math.min(42,260/items.length)}]}/><Text style={s.label}>{x.label}</Text></View>)}</View></View><Text style={{fontSize:6.5,textAlign:"center",marginTop:5}}>응답 항목</Text></View></>;
}
function DemographicPage({q,items,n,max=40}:{q:string,items:{label:string,value:number}[],n:number,max?:number}) { return <Page size="A4" style={s.page}><Text style={s.question}>{q}</Text><View style={{height:3,backgroundColor:C.cyan,marginBottom:8}}/><BarChart items={items} max={max} yLabel="비율"/><Footer n={n}/></Page>; }
function GenderAgePage({rows}:{rows:{label:string,segments:{name:string,count:number}[]}[]}) { const palette=["#ffe49a","#b9d7f5","#ffcda9","#d1d1d1"]; return <Page size="A4" style={s.page}><Text style={s.question}>성별과 연령대 교차 분석</Text><View style={{height:3,backgroundColor:C.cyan,marginBottom:14}}/><View style={{flexDirection:"row",justifyContent:"center",gap:8,marginBottom:14}}>{rows[0]?.segments.map((x,i)=><Text key={x.name} style={{fontSize:7,color:"#444"}}>■ <Text style={{color:palette[i]}}>{x.name}</Text></Text>)}</View><View style={{marginLeft:34,borderLeftWidth:.7,borderBottomWidth:.7,borderColor:"#888",paddingVertical:18}}>{rows.map(row=>{const total=row.segments.reduce((a,x)=>a+x.count,0);return <View key={row.label} style={{flexDirection:"row",height:54,alignItems:"center"}}><Text style={{position:"absolute",right:"100%",width:30,fontSize:7,textAlign:"right"}}>{row.label}</Text><View style={{flexDirection:"row",width:`${total/70*100}%`,height:34}}>{row.segments.map((x,i)=><View key={x.name} style={{width:`${x.count/total*100}%`,backgroundColor:palette[i],justifyContent:"center"}}><Text style={{fontSize:7,textAlign:"center"}}>{x.count}명</Text></View>)}</View></View>})}</View><Text style={{fontSize:7,textAlign:"center",marginTop:16}}>응답자 수</Text><Footer n={6}/></Page>; }
function QuantPage({roman,title,question,items,max,n,unit="점"}:{roman:string,title:string,question:string,items:{label:string,value:number}[],max:number,n:number,unit?:string}) { return <Page size="A4" style={s.page}><Header roman={roman} title={title} number="1" subtitle={`${title} 조사 결과`}/><Text style={s.question}>{question}</Text><View style={{height:3,backgroundColor:C.cyan,marginBottom:8}}/><BarChart items={items} max={max} suffix={unit} yLabel={unit==="%"?"비율":"평균 만족도"}/><View style={{marginTop:20}}><Text style={s.chartHead}>[ 정량 결과표 ]</Text>{items.map((x,i)=><View key={x.label} style={s.row}><Text style={[s.cell,{flex:.3}]}>{i+1}</Text><Text style={[s.cell,{flex:2}]}>{x.label}</Text><Text style={s.cell}>{x.value}{unit}</Text></View>)}</View><Footer n={n}/></Page>; }
function FeaturePage({name, mean, sd, distribution, first, n}:{name:string,mean:number,sd:number,distribution:{label:string,value:number}[],first:boolean,n:number}) { return <Page size="A4" style={s.page}>{first && <Header roman="III" title="기능별 고객 경험 평가" number="1" subtitle="기능별 고객 경험 조사 결과"/>}<Text style={s.question}>Q{6+n-8}. ‘{name}’ 기능의 만족도는 몇 점입니까?</Text><View style={{height:3,backgroundColor:C.cyan,marginBottom:8}}/><View style={{flexDirection:"row",borderWidth:.5,borderColor:C.line,backgroundColor:C.pale}}><Text style={{flex:2,textAlign:"center",padding:8,fontSize:12,fontWeight:"bold"}}>만족도 점수 평균 : {mean} / 10</Text><Text style={{flex:1,textAlign:"center",padding:8,fontSize:10,fontWeight:"bold",borderLeftWidth:.5,borderColor:C.line}}>표준편차 : {sd}</Text></View><View style={{marginTop:9}}><BarChart items={distribution} max={Math.max(...distribution.map(x=>x.value),1)+3} suffix=""/></View><View style={{marginTop:18,flexDirection:"row"}}><View style={{flex:1,borderWidth:.5,borderColor:C.line,minHeight:180,padding:10}}><Text style={{fontSize:11,fontWeight:"bold",textAlign:"center",backgroundColor:C.pale,padding:5,margin:-10,marginBottom:12}}>주관식 응답 감정 분석</Text><Text style={{fontSize:8,color:"#666",marginTop:45,textAlign:"center"}}>정성 분석 연결 전</Text></View><View style={{flex:1,borderWidth:.5,borderColor:C.line,minHeight:180,padding:10}}><Text style={{fontSize:11,fontWeight:"bold",textAlign:"center",backgroundColor:"#bdcae8",padding:5,margin:-10,marginBottom:12}}>응답 요약</Text><Text style={{fontSize:8,color:"#666",marginTop:45,textAlign:"center"}}>정성 분석 연결 전</Text></View></View><Footer n={n}/></Page>; }
function RankPage({importance,composition}:{importance:{name:string,score:number}[],composition:any[]}) { const ordered=[...importance].sort((a,b)=>b.score-a.score); return <Page size="A4" style={s.page}><Header roman="III" title="기능별 고객 경험 평가" number="2" subtitle="기능별 고객 경험 분석"/><Text style={s.question}>Q12. 캣독런의 기능 중 중요하다고 생각되는 순위를 1위부터 6위까지 순서대로 작성해주세요.</Text><View style={{height:3,backgroundColor:C.cyan,marginBottom:8}}/><RankCompositionChart rows={composition}/><View style={{marginTop:14,borderTopWidth:.6,borderLeftWidth:.6,borderColor:C.line}}><Text style={[tableCell,{backgroundColor:"#bdcae8",fontSize:11,fontWeight:"bold",textAlign:"center"}]}>기능별 중요 순위 종합</Text><View style={{flexDirection:"row",backgroundColor:"#f4f4f4"}}>{ordered.map((_,i)=><Text key={i} style={[tableCell,{flex:1,textAlign:"center",fontWeight:"bold"}]}>{i+1}위</Text>)}</View><View style={{flexDirection:"row"}}>{ordered.map(x=><Text key={x.name} style={[tableCell,{flex:1,textAlign:"center"}]}>{x.name}</Text>)}</View><View style={{flexDirection:"row"}}>{ordered.map(x=><Text key={x.name} style={[tableCell,{flex:1,textAlign:"center"}]}>{x.score}</Text>)}</View></View><Footer n={27}/></Page>; }
const rankColors=["#ff6b6b","#55c7c4","#47b1cc","#9dd1bb","#ffe69b","#d394db"];
function RankCompositionChart({rows}:{rows:any[]}) { const names=[...new Set(rows.flatMap(row=>row.segments.map((segment:any)=>segment.name)))]; return <View style={{borderWidth:.5,borderColor:"#aaa",padding:10,marginTop:10}}><View style={{flexDirection:"row",justifyContent:"center",gap:5,marginBottom:8}}>{names.map((name:string,i)=><Text key={name} style={{fontSize:5.5,color:rankColors[i]}}>■ <Text style={{color:"#444"}}>{name}</Text></Text>)}</View>{rows.map((row:any)=><View key={row.rank} style={{flexDirection:"row",height:26,alignItems:"center"}}><Text style={{width:24,fontSize:7}}>{row.rank}위</Text><View style={{height:17,flex:1,flexDirection:"row",borderWidth:.25,borderColor:"#ddd"}}>{row.segments.map((segment:any)=>{const color=rankColors[names.indexOf(segment.name)];return <View key={segment.name} style={{width:`${segment.percentage}%`,backgroundColor:color}}/>})}</View></View>)}</View>; }
function PriorityMatrixPage({importance,satisfaction}:{importance:any[],satisfaction:any[]}) { const byName=new Map(satisfaction.map(x=>[x.name,x.mean])); return <Page size="A4" style={s.page}><Text style={s.chartHead}>기능별 상대 중요도-만족도 그래프</Text><View style={{height:365,margin:14,borderWidth:1,borderColor:"#222",position:"relative",overflow:"hidden"}}>{Array.from({length:10},(_,i)=><View key={i} style={{position:"absolute",left:`${i*10}%`,top:0,bottom:0,borderLeftWidth:.35,borderColor:"#333"}}/>)}{Array.from({length:10},(_,i)=><View key={i} style={{position:"absolute",top:`${i*10}%`,left:0,right:0,borderTopWidth:.35,borderColor:"#333"}}/>)}<View style={{position:"absolute",left:"30%",right:0,top:"22%",bottom:0,backgroundColor:"#f8c69f",opacity:.72}}/><View style={{position:"absolute",left:0,right:"40%",top:0,bottom:"22%",backgroundColor:"#c9d4ea",opacity:.72}}/>{importance.map(item=>{const mean=byName.get(item.name)??0;const x=(item.score+5)*10;const y=(10-mean)*10;return <Text key={item.name} style={{position:"absolute",left:`${Math.max(1,Math.min(86,x))}%`,top:`${Math.max(2,Math.min(90,y))}%`,fontSize:8,fontWeight:"bold"}}>{item.name}</Text>})}</View><Text style={{fontSize:8,textAlign:"center",marginTop:-8}}>상대 중요도 (-5 ~ 5)</Text><Text style={{fontSize:8,marginTop:20,fontWeight:"bold"}}>영역별 참고 지표</Text><View style={{flexDirection:"row",borderTopWidth:.5,borderLeftWidth:.5,borderColor:"#777",marginTop:5}}>{[["긴급 개선","중요도가 높고 만족도가 낮음"],["중요 개선","중요도가 높고 만족도가 보통"],["개선 권장","중요도·만족도 중간"],["추후 고도화","만족도가 높음"]].map(([a,b])=><View key={a} style={{flex:1,borderRightWidth:.5,borderBottomWidth:.5,borderColor:"#777",padding:6}}><Text style={{fontSize:7,fontWeight:"bold"}}>{a}</Text><Text style={{fontSize:6,color:"#555"}}>{b}</Text></View>)}</View><Footer n={28}/></Page>; }
function ValuesDetailPage({values}:{values:any[]}) { const average=Number((values.reduce((sum,x)=>sum+x.value,0)/values.length).toFixed(2)); return <Page size="A4" style={s.page}><Header roman="V" title="4대 가치 만족도" number="2" subtitle="4대 가치 만족도 조사 결과 분석"/><Text style={s.chartHead}>4대 가치 만족도 종합 결과</Text><BarChart items={values} max={8} suffix="" yLabel="만족도 평균"/><View style={{marginTop:16,borderTopWidth:.5,borderLeftWidth:.5,borderColor:C.line}}><View style={{flexDirection:"row",backgroundColor:"#f2f2f2"}}><Text style={[tableCell,{width:90,fontWeight:"bold"}]}>가치</Text>{values.map(x=><Text key={x.label} style={[tableCell,{flex:1,textAlign:"center",fontWeight:"bold"}]}>{x.label}</Text>)}</View><View style={{flexDirection:"row"}}><Text style={[tableCell,{width:90,fontWeight:"bold"}]}>만족도</Text>{values.map(x=><Text key={x.label} style={[tableCell,{flex:1,textAlign:"center"}]}>{x.value}</Text>)}</View><View style={{flexDirection:"row"}}><Text style={[tableCell,{width:90,fontWeight:"bold"}]}>전체 평균</Text><Text style={[tableCell,{flex:1,textAlign:"center"}]}>{average}</Text></View></View><View style={{marginTop:22,borderTopWidth:.6,borderBottomWidth:.6,borderColor:C.line,padding:12}}><Text style={{fontSize:10,fontWeight:"bold"}}>4대 가치 만족도 종합 해석</Text><Text style={{fontSize:8,color:"#666",marginTop:8}}>정량 결과 기반 요약 영역입니다. 정성 분석이 연결되면 원본과 같은 서술형 분석과 제언이 이 위치에 추가됩니다.</Text></View><Footer n={36}/></Page>; }
function RadarChart({items,color}:{items:any[],color:string}) { const cx=115,cy=105,r=70,n=items.length;const point=(value:number,index:number)=>{const angle=-Math.PI/2+index*2*Math.PI/n;const radius=((value-4)/2.5)*r;return `${cx+Math.cos(angle)*radius},${cy+Math.sin(angle)*radius}`};const polygon=items.map((x,i)=>point(Number(x.value ?? x.mean ?? 4),i)).join(" ");return <View style={{alignItems:"center",marginTop:5}}><Svg width="230" height="210">{[.2,.4,.6,.8,1].map(scale=><Circle key={scale} cx={cx} cy={cy} r={r*scale} stroke="#d6d6d6" strokeWidth="1" fill="none"/>)}{items.map((_:any,i)=>{const angle=-Math.PI/2+i*2*Math.PI/n;return <Line key={i} x1={cx} y1={cy} x2={cx+Math.cos(angle)*r} y2={cy+Math.sin(angle)*r} stroke="#d6d6d6" strokeWidth="1"/>})}<Polygon points={polygon} fill={color} fillOpacity="0.35" stroke={color} strokeWidth="1.5"/></Svg></View>; }
function UxDetailPage({usability,fun}:{usability:any[],fun:any[]}) { const all=[...usability,...fun]; return <Page size="A4" style={s.page}><Header roman="VI" title="사용자 경험 품질 평가" number="2" subtitle="사용자 경험 품질 평가 결과 분석"/><Text style={{fontSize:11,fontWeight:"bold",textAlign:"center"}}>[전체]</Text><RadarChart items={all} color="#777"/><View style={{flexDirection:"row",marginTop:4}}><View style={{flex:1}}><Text style={{fontSize:10,fontWeight:"bold",textAlign:"center"}}>[실용성]</Text><RadarChart items={usability} color="#79a9ed"/></View><View style={{flex:1}}><Text style={{fontSize:10,fontWeight:"bold",textAlign:"center"}}>[즐거움]</Text><RadarChart items={fun} color="#f6bc65"/></View></View><View style={{marginTop:6,borderTopWidth:.5,borderLeftWidth:.5,borderColor:C.line}}>{[["실용성",usability],["즐거움",fun]].map(([group,items]:any)=><View key={group}><View style={{flexDirection:"row",backgroundColor:group==="실용성"?"#dce4f6":"#fcecc8"}}><Text style={[tableCell,{width:82,fontWeight:"bold",textAlign:"center"}]}>{group}</Text>{items.map((x:any)=><Text key={x.name} style={[tableCell,{flex:1,textAlign:"center",fontSize:6.5}]}>{x.name}</Text>)}</View><View style={{flexDirection:"row"}}><Text style={[tableCell,{width:82,textAlign:"center"}]}>점수</Text>{items.map((x:any)=><Text key={x.name} style={[tableCell,{flex:1,textAlign:"center"}]}>{x.mean}</Text>)}</View></View>)}</View><Footer n={39}/></Page>; }
function PriorServicePage({rate,mean,sd}:{rate:number,mean:number,sd:number}) { return <Page size="A4" style={s.page}><Header roman="III" title="기능별 고객 경험 평가" number="2" subtitle="유사 서비스 경험 조사 결과"/><Text style={s.question}>Q13. 캣독런 외에 다른 걷기 기반 서비스를 사용해 보신 적이 있나요?</Text><View style={{height:3,backgroundColor:C.cyan,marginBottom:8}}/><BarChart items={[{label:"사용 경험 있음",value:rate},{label:"사용 경험 없음",value:Number((100-rate).toFixed(1))}]} max={100} yLabel="비율"/><View style={{marginTop:25,borderTopWidth:.6,borderLeftWidth:.6,borderColor:C.line}}><Text style={[tableCell,{backgroundColor:"#bdcae8",fontSize:11,fontWeight:"bold",textAlign:"center"}]}>Q15. 유사 서비스 만족도</Text><View style={{flexDirection:"row"}}><Text style={[tableCell,{flex:1,textAlign:"center"}]}>평균 {mean}</Text><Text style={[tableCell,{flex:1,textAlign:"center"}]}>표준편차 {sd}</Text></View></View><Footer n={24}/></Page>; }
function OverallNpsDetailPage({distribution,overall,nps}:{distribution:any[],overall:any,nps:any}) { return <Page size="A4" style={s.page}><Header roman="VIII" title="종합 만족도 및 NPS 지수" number="1" subtitle="종합 만족도 및 NPS 지수"/><Text style={s.question}>Q35. 캣독런의 전반적인 만족도(종합 점수)는 몇 점입니까?</Text><View style={{height:3,backgroundColor:C.cyan,marginBottom:8}}/><BarChart items={distribution} max={Math.max(5,...distribution.map(x=>x.value))+3} suffix="" yLabel="응답자 수"/><View style={{marginTop:14,borderTopWidth:.6,borderLeftWidth:.6,borderColor:C.line}}><View style={{flexDirection:"row",backgroundColor:"#bdcae8"}}><Text style={[tableCell,{flex:1,textAlign:"center",fontWeight:"bold"}]}>종합 만족도 평균</Text><Text style={[tableCell,{flex:1,textAlign:"center",fontWeight:"bold"}]}>표준편차</Text><Text style={[tableCell,{flex:1,textAlign:"center",fontWeight:"bold"}]}>NPS 지수</Text></View><View style={{flexDirection:"row"}}><Text style={[tableCell,{flex:1,textAlign:"center",fontSize:12}]}>{overall.mean}</Text><Text style={[tableCell,{flex:1,textAlign:"center",fontSize:12}]}>{overall.sd}</Text><Text style={[tableCell,{flex:1,textAlign:"center",fontSize:12}]}>{nps.npsScore}</Text></View></View><Footer n={43}/></Page>; }
function ComparisonRadar({left,right}:{left:any[],right:any[]}) { const cx=105,cy=95,r=62,n=left.length; const polygon=(items:any[])=>items.map((item,i)=>{const angle=-Math.PI/2+i*2*Math.PI/n;const value=Number(item.mean??item.value??4);const radius=((value-3)/4)*r;return `${cx+Math.cos(angle)*radius},${cy+Math.sin(angle)*radius}`}).join(" ");return <Svg width="210" height="190">{[.25,.5,.75,1].map(scale=><Circle key={scale} cx={cx} cy={cy} r={r*scale} stroke="#ddd" strokeWidth="1" fill="none"/>)}{left.map((_:any,i)=>{const a=-Math.PI/2+i*2*Math.PI/n;return <Line key={i} x1={cx} y1={cy} x2={cx+Math.cos(a)*r} y2={cy+Math.sin(a)*r} stroke="#ddd" strokeWidth="1"/>})}<Polygon points={polygon(left)} fill="#78a9ed" fillOpacity="0.2" stroke="#78a9ed" strokeWidth="1.4"/><Polygon points={polygon(right)} fill="#ffb477" fillOpacity="0.2" stroke="#ffb477" strokeWidth="1.4"/></Svg>; }
function GenderComparisonPage({byGender}:{byGender:any[]}) { const features=byGender.map(group=>group.featureSatisfaction.map((x:any)=>({label:x.name,value:x.mean}))); const labels:{[key:string]:string}={functional:"기능적 가치",aesthetic:"심미적 가치",economic:"경제적 가치",social:"사회·공공적 가치"}; const values=byGender.map(group=>Object.entries(group.fourValues).map(([key,value])=>({label:labels[key],value:value as number}))); const usability=byGender.map(group=>group.uxQuality.usability); const fun=byGender.map(group=>group.uxQuality.fun); return <Page size="A4" style={s.page}><Text style={s.chartHead}>성별에 따른 차이</Text><View style={{flexDirection:"row",gap:10,marginTop:14}}><View style={{flex:1}}><Text style={{fontSize:9,fontWeight:"bold",textAlign:"center"}}>[기능별 만족도 차이]</Text><GroupedBars groups={features} series={byGender.map(x=>x.group)}/></View><View style={{flex:1}}><Text style={{fontSize:9,fontWeight:"bold",textAlign:"center"}}>[4대 가치 만족도 차이]</Text><GroupedBars groups={values} series={byGender.map(x=>x.group)}/></View></View><Text style={{fontSize:10,fontWeight:"bold",textAlign:"center",marginTop:16}}>[사용자 경험 품질 평가]</Text><View style={{flexDirection:"row",justifyContent:"space-around",marginTop:4}}><View><Text style={{fontSize:8,textAlign:"center"}}>실용성　<Text style={{color:"#78a9ed"}}>■</Text> {byGender[0]?.group}　<Text style={{color:"#ffb477"}}>■</Text> {byGender[1]?.group}</Text><ComparisonRadar left={usability[0]} right={usability[1]}/></View><View><Text style={{fontSize:8,textAlign:"center"}}>즐거움　<Text style={{color:"#78a9ed"}}>■</Text> {byGender[0]?.group}　<Text style={{color:"#ffb477"}}>■</Text> {byGender[1]?.group}</Text><ComparisonRadar left={fun[0]} right={fun[1]}/></View></View><Footer n={42}/></Page>; }
function NpsVisualPage({scores,nps}:{scores:number[],nps:any}) { const counts=Array.from({length:11},(_,score)=>scores.filter(x=>x===score).length); return <Page size="A4" style={s.page}><Header roman="VIII" title="종합 만족도 및 NPS 지수" number="1" subtitle="종합 만족도 및 NPS 지수"/><Text style={{fontSize:11,color:"#6f87b6",backgroundColor:C.pale,padding:8}}>NPS 지수 (Net Promoter Score : 순수 고객추천/구매 지수)</Text><View style={{borderWidth:.5,borderColor:"#ddd",padding:18,marginTop:2}}><View style={{flexDirection:"row",alignItems:"flex-end",justifyContent:"center",gap:2}}>{counts.map((count,score)=><View key={score} style={{alignItems:"center"}}><View style={{width:34,height:32,backgroundColor:score>=9?"#171717":score>=7?"#999":"#d8d8d8",justifyContent:"center"}}><Text style={{fontSize:8,textAlign:"center",color:score>=9?"white":"#444"}}>{score}</Text></View><Text style={{fontSize:6,marginTop:3}}>{count}명</Text></View>)}</View><Text style={{fontSize:7,textAlign:"center",marginTop:10}}>비추천 고객 0~6　　중립 고객 7~8　　추천/구매 고객 9~10</Text><View style={{backgroundColor:"#f3f3f3",padding:14,marginTop:18,flexDirection:"row",justifyContent:"space-around"}}><Text style={{fontSize:10}}>NPS{`\n`}{nps.npsScore}</Text><Text style={{fontSize:10}}>추천 고객 비율{`\n`}{nps.promoterPct}%</Text><Text style={{fontSize:10}}>비추천 고객 비율{`\n`}{nps.detractorPct}%</Text></View></View><View style={{marginTop:16,borderTopWidth:.5,borderColor:C.line,paddingTop:9}}><Text style={{fontSize:8}}>• NPS는 추천 고객 비율에서 비추천 고객 비율을 차감하여 산출합니다.</Text><Text style={{fontSize:8,marginTop:6}}>• 정성 해석과 개선 제언은 정성 분석 결과 연결 후 추가됩니다.</Text></View><View style={{marginTop:18,borderTopWidth:.5,borderLeftWidth:.5,borderColor:C.line}}><View style={{flexDirection:"row",backgroundColor:"#bdcae8"}}>{["평균 구매 의향","NPS 지수","구매 고객","중립 고객","비구매 고객"].map(x=><Text key={x} style={[tableCell,{flex:1,textAlign:"center",fontWeight:"bold"}]}>{x}</Text>)}</View><View style={{flexDirection:"row"}}>{[nps.rawMean,nps.npsScore,`${nps.promoterPct}%`,`${nps.passivePct}%`,`${nps.detractorPct}%`].map((x,i)=><Text key={i} style={[tableCell,{flex:1,textAlign:"center",fontSize:10}]}>{x}</Text>)}</View></View><Footer n={43}/></Page>; }
function FinalQuantSummaryPage({features,importance}:{features:any[],importance:any[]}) { const relative=new Map(importance.map(x=>[x.name,x.score])); return <Page size="A4" style={s.page}><Header roman="IX" title="종합 결과 및 제언" number="1" subtitle="사용성테스트 결과 요약"/><View style={{borderTopWidth:.5,borderLeftWidth:.5,borderColor:C.line}}><View style={{flexDirection:"row",backgroundColor:"#bdcae8"}}><Text style={[tableCell,{width:120,textAlign:"center",fontWeight:"bold"}]}>항목</Text><Text style={[tableCell,{flex:1,textAlign:"center",fontWeight:"bold"}]}>주요 의견</Text></View><View style={{flexDirection:"row"}}><Text style={[tableCell,{width:120,textAlign:"center",fontWeight:"bold",paddingTop:160}]}>기능별{`\n`}고객 경험 평가</Text><View style={{flex:1,padding:12}}><PriorityMatrixPage importance={importance} satisfaction={features}/></View></View></View><View style={{marginTop:12,borderTopWidth:.5,borderLeftWidth:.5,borderColor:C.line}}><View style={{flexDirection:"row",backgroundColor:"#f2f2f2"}}>{["기능명","평균 만족도","상대 중요도","긍정 비율","중립 비율","부정 비율"].map(x=><Text key={x} style={[tableCell,{flex:1,textAlign:"center",fontSize:7,fontWeight:"bold"}]}>{x}</Text>)}</View>{features.map((feature:any)=><View key={feature.name} style={{flexDirection:"row"}}><Text style={[tableCell,{flex:1,fontSize:6.5}]}>{feature.name}</Text><Text style={[tableCell,{flex:1,textAlign:"center"}]}>{feature.mean}</Text><Text style={[tableCell,{flex:1,textAlign:"center"}]}>{relative.get(feature.name)}</Text><Text style={[tableCell,{flex:1,textAlign:"center",color:"#777"}]}>정성 분석 대기</Text><Text style={[tableCell,{flex:1,textAlign:"center",color:"#777"}]}>정성 분석 대기</Text><Text style={[tableCell,{flex:1,textAlign:"center",color:"#777"}]}>정성 분석 대기</Text></View>)}</View><Footer n={50}/></Page>; }
function FinalQuantTablePage({features,importance}:{features:any[],importance:any[]}) { const relative=new Map(importance.map(x=>[x.name,x.score])); return <Page size="A4" style={s.page}><Header roman="IX" title="종합 결과 및 제언" number="1" subtitle="사용성테스트 결과 요약"/><Text style={s.chartHead}>기능별 고객 경험 평가 - 정량 종합</Text><Text style={{fontSize:8,color:"#666",marginVertical:10}}>중요도-만족도 매트릭스는 앞선 분석 페이지에 표시했으며, 아래 표는 raw data에서 직접 산출한 정량값입니다.</Text><View style={{borderTopWidth:.5,borderLeftWidth:.5,borderColor:C.line}}><View style={{flexDirection:"row",backgroundColor:"#bdcae8"}}>{["기능명","평균 만족도\n(점)","상대 중요도","긍정 비율\n(%)","중립 비율\n(%)","부정 비율\n(%)"].map(x=><Text key={x} style={[tableCell,{flex:1,textAlign:"center",fontSize:7,fontWeight:"bold"}]}>{x}</Text>)}</View>{features.map((feature:any)=><View key={feature.name} style={{flexDirection:"row"}}><Text style={[tableCell,{flex:1,fontSize:7}]}>{feature.name}</Text><Text style={[tableCell,{flex:1,textAlign:"center"}]}>{feature.mean}</Text><Text style={[tableCell,{flex:1,textAlign:"center"}]}>{relative.get(feature.name)}</Text><Text style={[tableCell,{flex:1,textAlign:"center",fontSize:6,color:"#777"}]}>정성 분석 대기</Text><Text style={[tableCell,{flex:1,textAlign:"center",fontSize:6,color:"#777"}]}>정성 분석 대기</Text><Text style={[tableCell,{flex:1,textAlign:"center",fontSize:6,color:"#777"}]}>정성 분석 대기</Text></View>)}</View><View style={{marginTop:22,borderTopWidth:.5,borderBottomWidth:.5,borderColor:C.line,padding:12}}><Text style={{fontSize:10,fontWeight:"bold"}}>정량 결과 활용 안내</Text><Text style={{fontSize:8,color:"#666",marginTop:8}}>평균 만족도와 상대 중요도는 현재 즉시 계산합니다. 긍정·중립·부정 비율 및 서술형 제언은 Claude 정성 분석 결과를 연결하면 같은 표의 빈 칸에 채워집니다.</Text></View><Footer n={50}/></Page>; }
function GroupedBars({groups,series}:{groups:{label:string,value:number}[][],series:string[]}) { const colors=["#b9d7f5","#ffcda9","#ffe49a","#d9ead3"]; return <View style={{borderWidth:.5,borderColor:"#aaa",height:220,padding:12}}><View style={{flexDirection:"row",justifyContent:"center",gap:8}}>{series.map((name,i)=><Text key={name} style={{fontSize:6,color:colors[i]}}>■ <Text style={{color:"#333"}}>{name}</Text></Text>)}</View><View style={{flex:1,flexDirection:"row",alignItems:"flex-end",justifyContent:"space-around",marginTop:12,borderBottomWidth:.5,borderLeftWidth:.5,borderColor:"#999"}}>{groups[0].map((entry,index)=><View key={entry.label} style={{width:58,alignItems:"center",flexDirection:"row",justifyContent:"center",height:155}}>{groups.map((group,i)=><View key={series[i]} style={{width:10,marginHorizontal:1,justifyContent:"flex-end",height:130}}><Text style={{fontSize:5,textAlign:"center"}}>{group[index].value}</Text><View style={{height:Math.max(2,(group[index].value-4)/5*105),backgroundColor:colors[i]}}/></View>)}<Text style={{position:"absolute",top:136,width:70,fontSize:5.5,textAlign:"center"}}>{entry.label}</Text></View>)}</View></View>; }
function CrossPage({byAge,byGender}:{byAge:any[],byGender:any[]}) { const featureGroups=byAge.map(group=>group.featureSatisfaction.map((x:any)=>({label:x.name,value:x.mean}))); const valueLabels:{[key:string]:string}={functional:"기능적 가치",aesthetic:"심미적 가치",economic:"경제적 가치",social:"사회·공공적 가치"}; const valueGroups=byGender.map(group=>Object.entries(group.fourValues).map(([label,value])=>({label:valueLabels[label]??label,value:value as number}))); return <Page size="A4" style={s.page}><Header roman="VII" title="교차 분석" number="1" subtitle="사용자 경험 품질 평가 결과 분석"/><Text style={{fontSize:11,fontWeight:"bold",textAlign:"center",marginBottom:7}}>[연령대별 기능별 만족도 차이]</Text><GroupedBars groups={featureGroups} series={byAge.map(x=>x.group)}/><Text style={{fontSize:11,fontWeight:"bold",textAlign:"center",marginTop:18,marginBottom:7}}>[성별 4대 가치 만족도 차이]</Text><GroupedBars groups={valueGroups} series={byGender.map(x=>x.group)}/><View style={{marginTop:18,borderTopWidth:.6,borderBottomWidth:.6,borderColor:C.line,padding:10}}><Text style={{fontSize:10,fontWeight:"bold"}}>[정량 분석 요약]</Text><Text style={{fontSize:8,color:"#666",marginTop:8}}>연령대와 성별별 평균은 raw data의 응답자 집단별 점수로 계산되었습니다. 정성 해석은 Claude 분석 결과가 연결되면 이 영역에 추가됩니다.</Text></View><Footer n={41}/></Page>; }
function PlaceholderPage({roman,title,subtitle,n}:{roman:string,title:string,subtitle:string,n:number}) { return <Page size="A4" style={s.page}><Header roman={roman} title={title} number="2" subtitle={subtitle}/><View style={{height:3,backgroundColor:C.cyan,marginBottom:14}}/><View style={{borderWidth:.6,borderColor:C.line,minHeight:420,padding:18}}><Text style={{fontSize:12,fontWeight:"bold",marginBottom:12}}>{subtitle}</Text><Text style={{fontSize:9,color:"#666",lineHeight:1.7}}>정성 분석 결과가 연결되면 원본 보고서와 같은 제목 행, 표, 요약 및 제언 블록으로 이 페이지를 채웁니다.</Text></View><Footer n={n}/></Page>; }
async function main() {
 const raw=readFileSync(path.join(process.cwd(),"data","[리바랩스]사용성테스트 raw data.xlsx"));
 const bytes=raw.buffer.slice(raw.byteOffset,raw.byteOffset+raw.byteLength) as ArrayBuffer;
 const workbook=parseWallaWorkbook(bytes);
 const records=normalizeWallaRows(workbook.headerRow,workbook.dataRows);
 const stats=computeQuantStats(records);
 overviewQuestions = buildSurveyQuestionRows(
  stats.featureSatisfaction.map((feature:any)=>feature.name),
  "캣독런",
 );
 const analysis={ featureScoreDistributions: stats.featureSatisfaction.map((_:unknown,index:number)=>Array.from({length:11},(_,score)=>records.filter(r=>r.featureSatisfaction[index]?.score===score).length)) };
 const age=stats.demographics.ageDistribution.map((x:any)=>({label:x.label,value:x.percentage})); const gender=[...stats.demographics.gender].sort((a:any,b:any)=>a.label.includes("남")?-1:b.label.includes("남")?1:0).map((x:any)=>({label:x.label,value:x.percentage}));
 const percentageDistribution=(values:(string|null|undefined)[],order:string[])=>order.map(label=>({label,value:Math.round(values.filter(value=>value===label).length/records.length*100)}));
 const walkTime=percentageDistribution(records.map(record=>record.avgWalkTime),["15분 미만","15분 이상 30분 미만","30분 이상 1시간 미만","1시간 이상 2시간 미만","2시간 이상"]);
 const frequencyOrder=["전혀 하지 않는다","1 ~ 2일 정도","3 ~ 4일 정도","5 ~ 6일 정도","매일 한다"];
 const walkFrequency=percentageDistribution(records.map(record=>record.walkFrequencyPerWeek?.replace(/~/g," ~ ").replace(/\s+/g," ").trim()),frequencyOrder);
 const featurePages=stats.featureSatisfaction.map((f:any,index:number)=>{ const counts=(analysis.featureScoreDistributions?.[index] ?? []).map((value:number,score:number)=>({label:String(score),value})); return <FeaturePage key={f.name} name={f.name} mean={f.mean} sd={f.sd} distribution={counts} first={index===0} n={8+index}/>; });
 const featureMeans=stats.featureSatisfaction.map((x:any)=>({label:x.name,value:x.mean}));
 const keyFactors=stats.keyFactorDistribution.map((x:any)=>({label:x.label.replace(/\s*\([^)]*\)\s*$/, ""),value:x.percentage}));
 const values=[{label:"기능적 가치",value:stats.fourValues.functional.mean},{label:"심미적 가치",value:stats.fourValues.aesthetic.mean},{label:"경제적 가치",value:stats.fourValues.economic.mean},{label:"사회·공공적 가치",value:stats.fourValues.social.mean}];
 const ux=[...stats.uxQuality.usability,...stats.uxQuality.fun].map((x:any)=>({label:x.name,value:x.mean}));
 const nps=[{label:"추천 고객",value:stats.nps.promoterPct},{label:"중립 고객",value:stats.nps.passivePct},{label:"비추천 고객",value:stats.nps.detractorPct}];
 const overallDistribution=Array.from({length:11},(_,score)=>({label:String(score),value:records.filter(record=>record.overallSatisfaction.score===score).length}));
 featurePages.push(
  <PriorityMatrixPage key="priority-matrix" importance={stats.relativeImportance} satisfaction={stats.featureSatisfaction}/>,
  <ValuesDetailPage key="value-detail" values={values}/>,
  <UxDetailPage key="ux-detail" usability={stats.uxQuality.usability} fun={stats.uxQuality.fun}/>,
 <PriorServicePage key="prior-service" rate={stats.demographics.priorServiceExperienceRate} mean={stats.demographics.priorServiceSatisfaction.mean} sd={stats.demographics.priorServiceSatisfaction.sd}/>,
 <OverallNpsDetailPage key="overall-nps" distribution={overallDistribution} overall={stats.overallSatisfaction} nps={stats.nps}/>,
  <GenderComparisonPage key="gender-comparison" byGender={stats.crossAnalysis.byGender}/>,
  <NpsVisualPage key="nps-visual" scores={records.map(record=>record.nps.score).filter((score):score is number=>score!==null)} nps={stats.nps}/>,
  <FinalQuantTablePage key="final-quant-table" features={stats.featureSatisfaction} importance={stats.relativeImportance}/>,
  );
 const doc=<Document title="리바랩스_원본재현_v2"><Page size="A4" style={s.page}><View style={{marginTop:190}}><Text style={{fontSize:30,fontWeight:"bold",color:"#08609d"}}>사용성 테스트</Text><Text style={{fontSize:30,fontWeight:"bold",color:"#08609d",marginTop:18}}>결과보고서</Text><Text style={{fontSize:26,color:"#6685ca",marginTop:32}}>리바랩스</Text><Text style={{fontSize:12,marginTop:16}}>Usability Test Proposal for ‘캣독런’</Text><Text style={{fontSize:10,marginTop:9}}>2025.09.05</Text></View><Text style={{position:"absolute",bottom:22,left:0,right:0,textAlign:"center",fontWeight:"bold",fontSize:13}}>ALPHA BROTHERS</Text></Page><TocPage/><Page size="A4" style={s.page}><Header roman="II" title="인적 사항 및 특성 조사" number="1" subtitle="인적 사항 및 특성 조사 결과"/><Text style={s.question}>Q1. 나이를 입력해주세요</Text><View style={{height:3,backgroundColor:C.cyan,marginBottom:8}}/><BarChart items={age} max={40} yLabel="비율"/><Text style={[s.question,{marginTop:22}]}>Q2. 성별을 선택해주세요</Text><View style={{height:3,backgroundColor:C.cyan,marginBottom:8}}/><BarChart items={gender} max={80} yLabel="비율"/><Footer n={6}/></Page><GenderAgePage rows={stats.demographics.genderByAgeBracket}/><DemographicPage n={7} max={60} q="Q3. 현재 사용하시는 스마트폰 운영체제를 선택해주세요" items={stats.demographics.os.map(x=>({label:x.label,value:x.percentage}))}/><DemographicPage n={7} max={40} q="Q4. 하루 평균 걷는 시간은 어느 정도 인가요?" items={walkTime}/><DemographicPage n={7} max={40} q="Q5. 일주일에 몇 일 정도 산책을 하시나요?" items={walkFrequency}/>{featurePages}<QuantPage roman="III" title="기능별 고객경험평가" question="기능별 만족도 종합" items={featureMeans} max={10} n={26}/><RankPage importance={stats.relativeImportance} composition={stats.rankPositionComposition}/><QuantPage roman="IV" title="핵심구매요소" question="핵심구매요소 응답 분포" items={keyFactors} max={40} n={30} unit="%"/><PlaceholderPage roman="IV" title="핵심구매요소" subtitle="핵심구매요소 분석" n={31}/><QuantPage roman="V" title="4대가치 만족도" question="4대 가치 만족도 조사 결과" items={values} max={10} n={32}/><PlaceholderPage roman="V" title="4대가치 만족도" subtitle="4대 가치 조사 결과 분석" n={36}/><QuantPage roman="VI" title="사용자 경험 품질 평가" question="실용성·즐거움 만족도" items={ux} max={10} n={39}/><CrossPage byAge={stats.crossAnalysis.byAgeGroup} byGender={stats.crossAnalysis.byGender}/><QuantPage roman="VIII" title="종합 만족도 및 NPS 지수" question={`NPS 지수: ${stats.nps.npsScore}`} items={nps} max={100} n={43} unit="%"/><PlaceholderPage roman="VIII" title="종합 만족도 및 NPS 지수" subtitle="개선 아이디어" n={45}/><PlaceholderPage roman="IX" title="종합 결과 및 제언" subtitle="사용성테스트 결과 요약" n={50}/><PlaceholderPage roman="IX" title="종합 결과 및 제언" subtitle="개선 전략 제언" n={53}/><PlaceholderPage roman="IX" title="종합 결과 및 제언" subtitle="기능별 고객 제언 종합" n={55}/></Document>;
 const out=await renderToBuffer(doc); const dir=path.join(process.cwd(),"output","pdf"); mkdirSync(dir,{recursive:true}); writeFileSync(path.join(dir,"리바랩스_원본재현_v2_독립렌더러.pdf"),out);
}
main();
